version: "3.4"

services:

  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: ${databaseUser}
      POSTGRES_PASSWORD: ${databasePassword}
      POSTGRES_DB: moodifyDb
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  frontend:
      build:
         context: ./frontend  
         dockerfile: Dockerfile  
         args:
           buildType: build-dc
      ports:
        - "80:80"
      restart: unless-stopped 

  backend:
    depends_on:
      database:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/moodifyDb
    build:
        context: ./backend  
        dockerfile: Dockerfile
    ports:
          - "8080:8080"
    restart: on-failure
    env_file:
      - .env

      
