version: "3.4"

services:
  frontend:
      build:
         context: ./frontend  
         dockerfile: Dockerfile  
         args:
           buildType: build-dc
      ports:
        - "80:80"
      restart: unless-stopped 

  backend:
    build:
        context: ./backend  
        dockerfile: Dockerfile  
    ports:
          - "8080:8080"
    restart: unless-stopped 
    env_file:
      - .env.dev

  database:
    image: postgres
    environment:
      POSTGRES_USER: moodify
      POSTGRES_PASSWORD: moodify
      POSTGRES_DB: moodifyDb
    volumes:
       - ./database/data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    env_file:
      - .env.dev
    restart: unless-stopped 
      
