name: Checks

on:
  pull_request:
    branches: 
      - 'main'
      - 'feature**'
    types: 
      - synchronize
      - ready_for_review

jobs:
  Check-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run tests
        run: |
          cd frontend
          npm test

      - name: Run lint
        run: |
          cd frontend
          npm run lint-ci

  Check-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: '3.8.3'

      - name: Build with Maven
        run: |
          cd backend
          mvn clean verify